### ISSUE TITLE
Modern OpenCL Resources

### ISSUE THREAD

**Issue by btilmon** [ProjectPhysX/OpenCL-Wrapper#5]
I was wondering if you could share modern OpenCL resources that you'd recommend? Or are the 2010 era books good enough?

**Comment by ProjectPhysX** [comment]
Hi @btilmon,

most helpful to me were:
- The book [OpenCL Programming Guide](https://ptgmedia.pearsoncmg.com/images/9780321749642/samplepages/0321749642.pdf)
- The [OpenCL Reference Guide](https://www.khronos.org/files/opencl30-reference-guide.pdf)

I have also recorded a talk on OpenCL programming on [YouTube](https://youtu.be/w4HEwdpdTns?si=2u9pK6CntMr1YH2K). The OpenCL language has not significantly chnged since the introduction of OpenCL 1.2 in 2011. In fact, OpenCL 1.2 is still the language standard that is used today in cross-vendor projects.

Have fun exploring the language!

Kind regards,
Moritz

PS: Posting an issue in one location is enough :)

**Comment by btilmon** [comment]
Thanks! Kind of time sensitive (:
